language: node_js
node_js: lts/*
deploy:
  provider: heroku
  api_key:
    secure: "Z4fMhRD8HXRM2LCuR7q1U+RIsROvEKz52bp+L39dPFexHPFjX+SBanJs1yDPQNI+mU5FeOwFBxwbWnQPRqR0CWySLmTQLrK5VjKrbgcCwoSjidThFdos/M2UeX/e2KrOP0T10ZWn2+49TX7k5shMchumI+kpEcu57cfSK6jr3gSYBIgkni1RQBr+KMuhMse5d5koEJVnGUfo6ZG4jVGu/OZlxmQI/Vioc2QZYoppW7ERGSWJgAvtcFlUWViAmrSMrwnYq038g2etceZ+Zls56kcTYbplOW5t68XgrvdXWE0Emn2njZkcED5kv8Cr9nOQvFTC/TLV0CK9ambdB7qVdOmL6GV663KMDTnJaPDJGiwBEqNhIlKYmPHxq2EbCtXvy7a01EJOA9vQhkRExQ5QjfQMiRsq/OAangZ3tKKDXE2JvUhyNMAd+vBxvH+sypuVWSuaNc5xJq4GHOX/CU0Zl7C6kiLFiQTW9fdWVGfigrcDfMHgxg6ydx8CHvFaYEdzYWPnSiI3sW4Yrccs0dQBcmCefdulqD/MKKkIe0D1q0kyvCHGWM0Nsod8t3eNsQatTHoZ77V7aKY66Q6f6PDFwNvX8F3OCZCTpg/5yph0lCOdw7EXg5dHBcfwwhIFLuUNmNov6UxmebBtFJ6fNMSZrNjdKpumxwFoh6vO3ZHg75Q="
  app: morgan-smartcar-backend
