language: node_js
node_js: lts/*
deploy:
  provider: heroku
  api_key:
    secure: hWmiEETHn9G7Q38Olfnr/OSY7Cfe+mnnvileNwFZ+lYVWqR+kh1yzJWKvSPLgW0aFqgqkSKnPZeMjTOKa8mN3bBq+fwNBXb8J+Bm+ycnFIhW0fvvvE/DwbKRvg2Vnc4e5oR/fmhrktB5n6kQFp02kjsb1tk9vCNtWkpVpGfXrp/mDh3BvQYJL67ppoXWYxImiuHjlzLJJ0a70w0NqJms+FXPuBiw4rW2p0xAWHtCcCh1tdH1hSqc4e1HaTSbwgtUbsOPXylOcVh+625pH8wPlISmTJsitovqpoSrzXGP6bcb1VBp3sQPM2XubZ1AiH7i+PH808CBUgziI1P8nkhVQBPR1HELJZ8lFT10bc0jHLboxi6Z60X4DJYr0REExm8/Z4jCDQ/vJpKTuRI3zBKD3DNneEXqrkiJiWg8VsnY1kovC13TpSCUFRW7BprQFiDQHOvXgIAsCTwGBZgF5f6kB+e2xj0QsPFQwta0mZc+1STI2SqTD2pjvk8EjP3HVgd9eLk2C+/AV7mZqJAoSAu8cUunNRO5//00jkQCW7CCtwu1SXNhVKNBlMZWnjHxzOfLZljSbZRYyWSkZbRM6xhMp5czF1a6awMnd+2K679IulnkNwSc42ng2HDeiaXezofY44dQ93OI3eVi0WeHpnsRr/85RL7l9EbgEy1zbMWjz48=
  app: morgan-smartcar-backend
